apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-oathkeeper
data:
  config.yaml: |
    serve:
      proxy:
        port: 4455 # run the proxy at port 4455
      api:
        port: 4456 # run the api at port 4456

    access_rules:
      repositories:
        - file:///etc/config/oathkeeper/rules.json

    errors:
      fallback:
        - json
      handlers:
        json:
          enabled: true
          config:
            verbose: true
        redirect:
          enabled: true
          config:
            to: https://www.ory.sh/docs

    mutators:
      header:
        enabled: true
        config:
          headers:
            X-User: "{{ print .Subject }}"
      noop:
        enabled: true
      id_token:
        enabled: true
        config:
          issuer_url: http://localhost:4455/
          jwks_url: file:///jwks.json

    authorizers:
      allow:
        enabled: true
      deny:
        enabled: true

    authenticators:
      anonymous:
        enabled: true
        config:
          subject: guest
      cookie_session:
        enabled: true
        config:
          check_session_url: http://kratos-service:4433/sessions/whoami
          preserve_path: true
          extra_from: "@this"
          subject_from: "identity.id"
          only:
            - ory_kratos_session
  rules.json: |
    [
      {
        "id": "api-public",
        "version": "v0.39.2",
        "match": {
          "url": "<http|https>://staging.twigslot.com/<.*>",
          "methods": [
            "GET",
            "POST",
            "PUT",
            "DELETE",
            "PATCH"
          ]
        },
        "authenticators": [
          { "handler": "cookie_session" },
          { "handler": "anonymous" }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "header"
          }
        ]
      }
    ]