apiVersion: apps/v1
kind: Deployment
metadata:
  name: oathkeeper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oathkeeper-pod
  template:
    metadata:
      labels:
        app: oathkeeper-pod
    spec:
      containers:
        - name: oathkeeper-container
          image: oryd/oathkeeper:v0.39.3
          args: ["serve", "--config", "/etc/config/oathkeeper/config.yaml"]
          ports:
          - containerPort: 4456
          volumeMounts: 
          - name: configmap-oathkeeper-volume
            mountPath: /etc/config/oathkeeper
      volumes:
        - name: configmap-oathkeeper-volume
          configMap:
            name: configmap-oathkeeper
---
apiVersion: v1
kind: Service
metadata:
  name: oathkeeper-service
spec:
  selector:
    app: oathkeeper-pod
  # type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4456
      targetPort: 4456
      # nodePort: 30003
      name: http