apiVersion: apps/v1
kind: Deployment
metadata:
  name: selfservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selfservice-pod
  template:
    metadata:
      labels:
        app: selfservice-pod
    spec:
      containers:
      - name: kratos-selfservice-ui-node
        image: oryd/kratos-selfservice-ui-node:v0.9.0-alpha.2
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: KRATOS_PUBLIC_URL
          value: http://kratos-service:4433/
        - name: KRATOS_BROWSER_URL
          value: https://staging.twigslot.com/kratos
        - name: BASE_PATH
          value: https://staging.twigslot.com/auth
---
apiVersion: v1
kind: Service
metadata:
  name: selfservice-service
spec:
  selector:
    app: selfservice-pod
  ports:
    - protocol: TCP
      port: 4455
      targetPort: 3000
      # nodePort: 30000
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kratos-deployment
spec:
  serviceName: kratos-statefulset
  replicas: 1
  selector:
    matchLabels:
      app: kratos-pod
  template:
    metadata:
      labels:
        app: kratos-pod
    spec:
      volumes:
        - name: sqlite-pv-storage
          persistentVolumeClaim:
            claimName: twig-pvc
            # claimName: ebs-claim
        - name: configmap-kratos-volume
          configMap:
            name: configmap-kratos
      containers:
      - name: kratos-pod-container
        image: oryd/kratos:v0.9.0-alpha.2
        ports:
        - containerPort: 4433 # public
        - containerPort: 4434 # admin (not in use)
        env:
        - name: DSN
          value: sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
        volumeMounts: 
        - name: sqlite-pv-storage
          mountPath: /var/lib/sqlite
        - name: configmap-kratos-volume
          mountPath: /etc/config/kratos
        args: ["serve","-c","/etc/config/kratos/kratos.yml","--dev","--watch-courier"]
      securityContext:
        fsGroup: 10000
---
apiVersion: v1
kind: Service
metadata:
  name: kratos-service
spec:
  selector:
    app: kratos-pod
  ports:
    - name: public
      protocol: TCP
      port: 4433
      targetPort: 4433
    - name: admin
      protocol: TCP
      port: 4434
      targetPort: 4434
      # nodePort: 30006
  # type: LoadBalancer